print('Welcome to Space Dungeon')
print('Please enter your name.')
Name = input()
print('Welcome, ' + Name + '.' ' Please select a class from the choices below.')
print('Soldier - Fighters with higher than average attack and lower than average magic.')
print('Rogue - Skillful with relatively average attack and magic abilities.')
print('Wizard - Magic users with high magic and lower than average attack power.')
print('Knight - Armored fighters with average leveles of magic and attack power.')
print('Technician - Skilled engineers with high attack power and very low magic.')
Class = input()
print('Now allocate points towards attack and magic power out of 100 total points.')
print('Points for Attack')
Attack = input()
print('Points for Magic')
Magic = input()
print('You have chosen to be a ' + Class + ' with ' + Attack + ' attack power and ' + Magic + ' magic power.')
