print('Welcome to Space Dungeon')
print('Please enter your name.')
Name = input()
print('Welcome, ' + Name + '.' ' Please select a class from the choices below.')
print('Soldier - Trained fighters with formal military training. High attack and lower magic average.')
print('Mercenary - Skillful warriors for hire. with relatively average attack and magic abilities.')
print('Wizard - Magic users with high degrees of intelligence and power.')
print('Knight - Armored fighters with a code of honor.')
print('Technician - Skilled engineers with technical based combat abilities and expertise.')
Class = input()
print('Now allocate points towards attack and magic power out of 100 total points.')
print('Points for Attack')
Attack = input()
print('Points for Magic')
Magic = input()
print('You have chosen to be a ' + Class + ' with ' + Attack + ' attack power and ' + Magic + ' magic power.')
